config/routes.rb
Sevn::Application.routes.draw do
  get "users/new"

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/plans', :to => 'pages#plans'
  match '/signup', :to => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact Us"
  end

  def about
    @title = "About Us"
  end
  
  def plans
    @title = "Plans and Pricing"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign Up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logo
    image_tag("logo.png")
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<div id="footer">
<p><small>Copyright 2011 | Wide Eyed Media, Inc.</small></p>
</div>

app/views/layouts/_header.html.erb
<div id="logo">
	<%= link_to logo, root_path %>
</div>

<div id="navigation">
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About Sevn", about_path %></li>
		<li><%= link_to "Plans/Pricing", plans_path %></li>
		<li><%= link_to "Create an Account", signup_path %></li>
	</ul>	
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
<!--[if lt IE 8]>
<%= stylesheet_link_tag 'blueprint/ie' %>
<![endif]-->
<%= stylesheet_link_tag 'customer', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Sevn - A simple todo list for the next seven days | <%= @title %></title>
<%= render 'layouts/stylesheets' %>
</head>
<body>


<div id="wrap">

<%= render 'layouts/header'%>

<div id="body">
<%= yield %>
</div>

<%= render 'layouts/footer'%>

</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Sevn is a simple todo list application that only shows tasks for the next week.  This focuses the user on the tasks that are immediately achievable.</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Sevn is a simple todo list application that only shows tasks for the next week.  This focuses the user on the tasks that are immediately achievable.</p>

app/views/pages/home.html.erb
<h1>What is <strong>Sevn</strong>?</h1>
<p><strong>Sevn</strong> is a simple todo list application that only shows tasks for the next week. This focuses the user on the tasks that are immediately achievable.</p>
<h1>How many ways can I access <strong>Sevn</strong>?</h1>
<p><strong>Sevn</strong> will be deployed as a web application built with Ruby on Rails and an iOS application built with Sencha touch and deployed with PhoneGap.</p>
<h1>When can I start using <strong>Sevn</strong>?</h1>
<p><strong>Sevn</strong> on the web will be ready to begin beta testing in February of 2011.</p>

app/views/pages/plans.html.erb
<h1>Pricing Plans</h1>
<p>Sevn is a simple todo list application that only shows tasks for the next week.  This focuses the user on the tasks that are immediately achievable.</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>Signup will begin in a few weeks.</p>